
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=development
      - PORT=3030
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "server.js"]

